# Generated by Django 3.2.7 on 2021-09-18 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PostosDeTrabalho', '0002_auto_20210916_0957'),
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor', models.FloatField()),
                ('PostoDeTrabalho_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PostosDeTrabalho.postodetrabalho')),
                ('cliente_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_id', to='Clientes.clientes')),
                ('cliente_nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientes', verbose_name='Nome do Cliente')),
            ],
        ),
    ]
