# Generated by Django 3.2.7 on 2021-09-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='PostoDeTrabalho_id',
            new_name='PostoDeTrabalho',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cliente_nome',
        ),
    ]
