# Generated by Django 3.2.7 on 2021-09-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostosDeTrabalho', '0002_auto_20210916_0957'),
        ('Contratos', '0002_auto_20210917_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='PostoDeTrabalho',
        ),
        migrations.AddField(
            model_name='contrato',
            name='postoDeTrabalho',
            field=models.ManyToManyField(to='PostosDeTrabalho.PostoDeTrabalho'),
        ),
    ]
