# Generated by Django 3.2.7 on 2021-09-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostosDeTrabalho', '0003_postodetrabalho_colaborador'),
        ('Contratos', '0003_auto_20210917_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='postoDeTrabalho',
        ),
        migrations.AddField(
            model_name='contrato',
            name='postoDeTrabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postoDeTrabalho', to='PostosDeTrabalho.postodetrabalho'),
        ),
    ]
