# Generated by Django 3.2.7 on 2021-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostosDeTrabalho', '0003_postodetrabalho_colaborador'),
        ('Contratos', '0004_auto_20210918_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='postoDeTrabalho',
        ),
        migrations.AddField(
            model_name='contrato',
            name='postoDeTrabalho',
            field=models.ManyToManyField(related_name='postoDeTrabalho', to='PostosDeTrabalho.PostoDeTrabalho'),
        ),
    ]
