# Generated by Django 3.2.4 on 2021-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0007_alter_colaborador_cpf'),
        ('QuadroDePresenca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadrodepresenca',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, to='Colaboradores.Colaborador'),
        ),
    ]
