# Generated by Django 3.2.4 on 2021-09-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0007_alter_colaborador_cpf'),
        ('QuadroDePresenca', '0002_quadrodepresenca_colaboradores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.TextField(max_length=8)),
                ('ano', models.TextField()),
                ('dia', models.TextField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='quadrodepresenca',
            name='colaboradores',
        ),
        migrations.AddField(
            model_name='quadrodepresenca',
            name='colaboradores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.colaborador'),
        ),
        migrations.AlterField(
            model_name='quadrodepresenca',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QuadroDePresenca.data'),
        ),
    ]
