# Generated by Django 3.2.4 on 2021-10-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colaboradores', '0007_alter_colaborador_cpf'),
        ('PostosDeTrabalho', '0005_remove_postodetrabalho_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alocacao', models.BooleanField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.colaborador')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostosDeTrabalho.postodetrabalho')),
            ],
        ),
    ]
