# Generated by Django 3.2.4 on 2021-10-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0007_alter_colaborador_cpf'),
        ('PostosDeTrabalho', '0005_remove_postodetrabalho_colaborador'),
        ('Alocacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.colaborador'),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PostosDeTrabalho.postodetrabalho'),
        ),
    ]
