# Generated by Django 3.2.4 on 2021-10-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('colaborador_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.colaborador')),
                ('quant_presenca', models.IntegerField(null=True, blank=True)),
            ],
        ),
    ]
