# Generated by Django 3.2.7 on 2021-09-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='funcao',
            new_name='endereco',
        ),
    ]
