# Generated by Django 3.2.4 on 2021-09-16 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PostosDeTrabalho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postodetrabalho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postodetrabalho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
