# Generated by Django 3.2.7 on 2021-09-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0005_auto_20210916_0951'),
        ('PostosDeTrabalho', '0002_auto_20210916_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='postodetrabalho',
            name='colaborador',
            field=models.ManyToManyField(to='Colaboradores.Colaborador'),
        ),
    ]
