# Generated by Django 3.2.7 on 2021-09-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0005_auto_20210916_0951'),
        ('PostosDeTrabalho', '0003_postodetrabalho_colaborador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postodetrabalho',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='postodetrabalho',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Colaboradores.colaborador'),
        ),
    ]
