# Generated by Django 3.2.4 on 2021-11-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostosDeTrabalho', '0005_remove_postodetrabalho_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='postodetrabalho',
            name='limites_multa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
