# Generated by Django 3.2.4 on 2021-10-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colaboradores', '0007_alter_colaborador_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuadroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.BooleanField(default=False)),
                ('colaboradores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.colaborador')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QuadroPresenca.data')),
            ],
        ),
    ]
