# Generated by Django 3.2.7 on 2021-10-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuadroPresenca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadropresenca',
            name='data',
        ),
        migrations.AddField(
            model_name='quadropresenca',
            name='data',
            field=models.ManyToManyField(to='QuadroPresenca.Data'),
        ),
    ]
