# Generated by Django 3.2.4 on 2021-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuadroPresenca', '0003_alter_data_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='quadropresenca',
            old_name='data',
            new_name='data_id',
        ),
        migrations.AddField(
            model_name='data',
            name='dia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='month',
            field=models.TextField(blank=True, null=True),
        ),
    ]
