# Generated by Django 3.2.4 on 2021-11-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0007_alter_colaborador_cpf'),
        ('QuadroPresenca', '0005_quadropresenca_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_presenca', models.IntegerField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.colaborador')),
            ],
        ),
    ]
