# Generated by Django 3.2.7 on 2021-09-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('matricula', models.TextField()),
                ('nomeCompleto', models.TextField(max_length=255)),
                ('dataAdmissao', models.DateField()),
                ('dataDemissao', models.DateField()),
                ('funcao', models.TextField(max_length=255)),
                ('tipoDeCobertura', models.CharField(choices=[('fixa', 'FIXA'), ('flutuante', 'FLUTUANTE')], max_length=9)),
                ('situacaoCadastro', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
