# Generated by Django 3.2.7 on 2021-09-30 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostosDeTrabalho', '0005_remove_postodetrabalho_colaborador'),
        ('Colaboradores', '0005_auto_20210916_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='posto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PostosDeTrabalho.postodetrabalho'),
        ),
    ]
