# Generated by Django 3.2.7 on 2021-09-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0006_colaborador_posto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
